name: NucleiFuzzer Parallel Scan and Commit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y git python3 python3-pip golang curl unzip xargs

        # Install Nuclei
        curl -sSfL https://github.com/projectdiscovery/nuclei/releases/latest/download/nuclei-linux-amd64.tar.gz | tar -xz -C /usr/local/bin

        # Install httpx
        curl -sSfL https://github.com/projectdiscovery/httpx/releases/latest/download/httpx-linux-amd64.tar.gz | tar -xz -C /usr/local/bin

        # Install ParamSpider
        git clone https://github.com/devanshbatham/ParamSpider.git
        cd ParamSpider && pip3 install -r requirements.txt
        cd ..

    - name: Clone NucleiFuzzer
      run: |
        git clone https://github.com/0xKayala/NucleiFuzzer.git
        chmod +x NucleiFuzzer/install.sh
        chmod +x NucleiFuzzer/NucleiFuzzer.sh
        ./NucleiFuzzer/install.sh

    - name: Create output directories
      run: mkdir -p output/domains output/errors

    - name: Run NucleiFuzzer in parallel (safe filenames)
      run: |
        cat Input/domains.txt | xargs -P 5 -I {} bash -c '
          safe_name=$(echo "{}" | sed "s/[^a-zA-Z0-9_-]/_/g")
          ./NucleiFuzzer/NucleiFuzzer.sh -d "{}" -o "output/domains/${safe_name}.txt" || echo "Error scanning {}" >> output/errors/errors.log
        '

    - name: Commit results back to repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add output/domains output/errors
        git commit -m "Add NucleiFuzzer scan results [skip ci]" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
