name: Recon Workflow

on:
  workflow_dispatch:

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest stable

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y golang-go python3 python3-pip git build-essential

      # Clone and install tools
      - name: Clone and install tools
        run: |
          # Nuclei
          git clone https://github.com/projectdiscovery/nuclei.git
          cd nuclei && go install ./... && cd ..

          # ParamSpider
          git clone https://github.com/0xKayala/ParamSpider.git
          pip3 install -r ParamSpider/requirements.txt

          # waybackurls
          git clone https://github.com/tomnomnom/waybackurls.git
          cd waybackurls && go install ./... && cd ..

          # gauplus
          git clone https://github.com/bp0lr/gauplus.git
          cd gauplus && go install ./... && cd ..

          # hakrawler
          git clone https://github.com/hakluke/hakrawler.git
          cd hakrawler && go install ./... && cd ..

          # katana
          git clone https://github.com/projectdiscovery/katana.git
          cd katana && go install ./... && cd ..

          # httpx
          git clone https://github.com/projectdiscovery/httpx.git
          cd httpx && go install ./... && cd ..

          # uro
          git clone https://github.com/s0md3v/uro.git
          pip3 install ./uro

          # Nuclei Templates
          git clone https://github.com/projectdiscovery/nuclei-templates.git nuclei-templates

      - name: Verify tools installation
        run: |
          nuclei -version
          httpx -version
          gauplus -h
          hakrawler -h
          katana -h
          waybackurls -h
          python3 ParamSpider/paramspider.py -h
          uro -h || echo "uro installed"

      - name: Run Recon Pipeline
        run: |
          # Ensure domains.txt exists
          if [ ! -f domains.txt ]; then
            echo "domains.txt not found. Please add it to the repository root."
            exit 1
          fi

          # Deduplicate domains
          sort -u domains.txt > targets.txt

          # Collect URLs from multiple tools
          cat targets.txt | gauplus > gauplus.txt
          cat targets.txt | waybackurls > waybackurls.txt
          cat targets.txt | hakrawler > hakrawler.txt
          katana -list targets.txt -silent -o katana.txt

          # Optional ParamSpider run (slower, can comment out if not needed)
          while read domain; do
            python3 ParamSpider/paramspider.py -d "$domain" -o "paramspider_$domain.txt"
          done < targets.txt

          # Merge & deduplicate URLs
          cat gauplus.txt waybackurls.txt hakrawler.txt katana.txt paramspider_*.txt 2>/dev/null | uro | sort -u > urls.txt

          # Probe live hosts
          cat targets.txt | httpx -silent -o live_hosts.txt

          # Run nuclei scan
          nuclei -l urls.txt -t nuclei-templates -o nuclei_results.txt

      - name: Upload results
        uses: actions/upload-artifact@v4  # Updated to latest stable
        with:
          name: recon-results
          path: |
            targets.txt
            live_hosts.txt
            urls.txt
            nuclei_results.txt
            paramspider_*.txt
