name: Httpx - Alive Subdomains Per Domain

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main

jobs:
  httpx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Httpx
        run: |
          curl -s https://api.github.com/repos/projectdiscovery/httpx/releases/latest \
            | grep "browser_download_url.*linux_amd64.zip" \
            | cut -d '"' -f 4 \
            | wget -qi -
          unzip -o httpx_*_linux_amd64.zip httpx
          sudo rm -rf /usr/local/bin/httpx   # delete old dir or binary
          sudo install -m 755 httpx /usr/local/bin/httpx
          httpx -version

      - name: Run Httpx for each domain's subdomain file
        run: |
          for file in output/*.txt; do
            domain=$(basename "$file" .txt)
            echo "[*] Running httpx for $domain"
            if [ -s "$file" ]; then
              httpx -silent -l "$file" -o "output/${domain}_live.txt"
            else
              echo "[-] Skipping $domain (empty file)"
            fi
          done

      - name: Show results
        run: ls -lh output && head -n 10 output/*_live.txt || echo "No live results"

      - name: Commit results back to repo
        run: |
          git config --global u
