name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # allows manual trigger

jobs:
  setup-and-scan:
    runs-on: ubuntu-latest
    env:
      TOOLS_DIR: $HOME/tools
      PATH: $HOME/tools/bin:$PATH
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      # Cache Go modules and binaries
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            $HOME/tools/bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Cache Python pip packages
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Create tools directory
      - name: Create tools directory
        run: mkdir -p $HOME/tools/bin

      # Install Go-based tools
      - name: Install Nuclei
        run: GO111MODULE=on go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest

      - name: Install waybackurls
        run: go install github.com/tomnomnom/waybac
