name: Nuclei - Vulnerability Scan

on:
  workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Run Nuclei Scan
      - name: Nuclei - Vulnerability Scan
        id: nuclei_scan
        uses: projectdiscovery/nuclei-action@main
        with:
          urls: Input/domains.txt
          flags: "-severity critical,high,medium,low -stats -o nuclei.txt -report-format sarif -o nuclei.sarif"

      # Ensure bbp folder exists
      - name: Create BBP folder if missing
        run: mkdir -p bbp

      # Move scan results to bbp folder
      - name: Move Scan Results
        run: |
          mv nuclei.txt bbp/nuclei.txt
          mv nuclei.sarif bbp/nuclei.sarif

      # Commit results back to repository
      - name: Commit and Push Scan Results
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add bbp/nuclei.txt bbp/nuclei.sarif
          git commit -m "Update Nuclei scan results"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload Nuclei artifact
      - name: Upload Nuclei Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-results
          path: bbp/nuclei.txt

      # Upload SARIF to GitHub Security Dashboard
      - name: Upload SARIF to GitHub Security Dashboard
        if: steps.nuclei_scan.outputs.sarif_exists == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bbp/nuclei.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
