name: NucleiFuzzer

on:
  workflow_dispatch:
  push:
    paths:
      - "Input/domains.txt"

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Tools
        run: |
          sudo apt update -y
          sudo apt install -y python3 python3-pip git wget curl

          # Install ParamSpider via pip
          pip3 install paramspider

          # Install Go tools
          go install github.com/tomnomnom/waybackurls@latest
          go install github.com/bp0lr/gauplus@latest
          go install github.com/hakluke/hakrawler@latest
          go install github.com/projectdiscovery/katana/cmd/katana@latest
          go install github.com/projectdiscovery/httpx/cmd/httpx@latest
          go install github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest

          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Run Recon Tools
        run: |
          mkdir -p Output
          while read domain; do
            echo "[*] Processing $domain"

            # ParamSpider
            paramspider -d $domain --quiet --level high -o Output/${domain}_paramspider.txt

            # waybackurls
            echo $domain | waybackurls > Output/${domain}_wayback.txt

            # gauplus
            echo $domain | gauplus -t 5 > Output/${domain}_gauplus.txt

            # hakrawler
            echo $domain | hakrawler -depth 3 -scope subs > Output/${domain}_hakrawler.txt

            # katana
            katana -u $domain -d 3 -silent > Output/${domain}_katana.txt
          done < Input/domains.txt

          # Merge all results & filter live URLs with httpx
          cat Output/* | sort -u | httpx -silent -status-code -title -follow-redirects -no-color -o Output/live_urls.txt

      - name: Run Nuclei (Critical/High/Medium/Low only)
        run: |
          mkdir -p Output/nuclei-results
          nuclei -l Output/live_urls.txt \
            -t nuclei-templates/ \
            -severity critical,high,medium,low \
            -o Output/nuclei-results/nuclei_report.txt

      - name: Commit results back to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Output/
          git commit -m "Automated scan results [skip ci]" || echo "No changes to commit"
          git push
