name: Nuclei - Per Domain Scan

on:
  workflow_dispatch:
    inputs:
      severity:
        description: "Global severity levels (default: critical,high,medium,low)"
        required: false
        default: "critical,high,medium,low"
      threads:
        description: "Concurrent threads per domain (default: 50)"
        required: false
        default: "50"
      parallel_domains:
        description: "Number of domains scanned in parallel (default: 5)"
        required: false
        default: "5"
      timeout:
        description: "Timeout per domain in minutes (default: 10)"
        required: false
        default: "10"
      output_folder:
        description: "Folder to save results (default: result)"
        required: false
        default: "result"
  push:
    branches:
      - main

jobs:
  nuclei:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Nuclei
        run: |
          go install github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
          nuclei -version

      - name: Ensure output folder exists
        run: mkdir -p "${{ github.event.inputs.output_folder || 'result' }}"

      - name: Cache Nuclei Templates
        uses: actions/cache@v3
        with:
          path: ~/.nuclei-templates
          key: nuclei-templates-${{ runner.os }}
          restore-keys: |
            nuclei-templates-

      - name: Update Nuclei templates
        run: nuclei -update-templates || true

      - name: Run Nuclei Scans in Parallel with SARIF
        continue-on-error: true
        run: |
          OUTPUT_FOLDER=${{ github.event.inputs.output_folder || 'result' }}
          DEFAULT_SEVERITY=${{ github.event.inputs.severity || 'critical,high,medium,low' }}
          THREADS=${{ github.event.inputs.threads || 50 }}
          PARALLEL=${{ github.event.inputs.parallel_domains || 5 }}
          TIMEOUT=${{ github.event.inputs.timeout || 10 }}

          # Temporary file for per-domain severity overrides
          OVERRIDES_FILE=$(mktemp)
          if [[ -f nuclei-domain-overrides.csv ]]; then
            tail -n +2 nuclei-domain-overrides.csv >> "$OVERRIDES_FILE"
          fi

          run_scan() {
            file="$1"
            domain=$(basename "$file" _live.txt)
            SEVERITY="$DEFAULT_SEVERITY"

            # Apply per-domain severity override if present
            if [[ -f "$OVERRIDES_FILE" ]]; then
              line=$(grep -E "^$domain," "$OVERRIDES_FILE" || true)
              if [[ -n "$line" ]]; then
                IFS=, read -r _ _ severity <<< "$line"
                [[ -n "$severity" ]] && SEVERITY="$severity"
              fi
            fi

            echo "[*] Scanning $domain with threads=$THREADS, timeout=${TIMEOUT}m..."
            timeout "${TIMEOUT}m" nuclei -l "$file" \
              -severity "$SEVERITY" \
              -c "$THREADS" \
              -o "${OUTPUT_FOLDER}/${domain}_nuclei.txt" \
              -reporter sarif \
              -o "${OUTPUT_FOLDER}/${domain}_nuclei.sarif" \
              || echo "[-] Scan failed or timed out for $domain, continuing..."
          }

          export -f run_scan
          export OUTPUT_FOLDER DEFAULT_SEVERITY THREADS OVERRIDES_FILE TIMEOUT

          find live -name '*_live.txt' | xargs -P "$PARALLEL" -I {} bash -c 'run_scan "$@"' _ {}

      - name: Commit and Push Scan Results
        run: |
          OUTPUT_FOLDER=${{ github.event.inputs.output_folder || 'result' }}
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add "${OUTPUT_FOLDER}"/*.txt "${OUTPUT_FOLDER}"/*.sarif
          git diff --cached --quiet || git commit -m "Update Nuclei scan results"
          git fetch origin main
          git rebase origin/main
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Nuclei Results Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-results-${{ github.sha }}-${{ github.ref_name }}
          path: "${{ github.event.inputs.output_folder || 'result' }}/"
