name: Nuclei - Per Domain Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  nuclei:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Ensure result folder exists
      - name: Create result folder
        run: mkdir -p result

      # Cache Nuclei templates
      - name: Cache Nuclei Templates
        uses: actions/cache@v3
        with:
          path: ~/.nuclei-templates
          key: nuclei-templates-${{ runner.os }}-${{ hashFiles('**/nuclei-templates/**') }}
          restore-keys: |
            nuclei-templates-

      # Run Nuclei per domain with exclusions and SARIF
      - name: Run Nuclei Scans
        id: nuclei_scan
        uses: projectdiscovery/nuclei-action@main
        with:
          urls: output/domain.txt
          flags: "-severity critical,high,medium,low -stats -o result/nuclei.txt"
          sarif: true
          exclude-templates: "http/default-logins,code,code/cves,http/cnvd"

      # Commit and push results if changes exist
      - name: Commit and Push Scan Results
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add result/nuclei.txt result/nuclei.sarif
          if ! git diff --cached --quiet; then
            git commit -m "Update Nuclei scan results in result folder"
            git pull --rebase
            git push
          else
            echo "No changes detected. Skipping commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload Nuclei text artifact
      - name: Upload Nuclei Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-results
          path: result/nuclei.txt

      # Upload SARIF to GitHub Security Dashboard
      - name: Upload SARIF to GitHub Security Dashboard
        if: steps.nuclei_scan.outputs.sarif_exists == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: result/nuclei.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
