name: Nuclei - Per Domain Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  nuclei:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # Install latest Nuclei v3.x via Go
      - name: Install Latest Nuclei
        run: |
          # Remove any old nuclei binaries
          rm -f /usr/local/bin/nuclei
          rm -f $HOME/go/bin/nuclei
          
          # Install latest nuclei v3.x
          go install github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
          echo "export PATH=$PATH:$HOME/go/bin" >> $GITHUB_ENV

      # Confirm installed version
      - name: Confirm Nuclei version
        run: |
          $HOME/go/bin/nuclei -version

      # Update templates
      - name: Update Nuclei templates
        run: |
          $HOME/go/bin/nuclei -update-templates

      # Run Nuclei per domain
      - name: Run Nuclei Scans
        run: |
          mkdir -p result
          for file in live/*_live.txt; do
            domain=$(basename "$file" _live.txt)
            echo "[*] Running Nuclei scan for $domain"
            $HOME/go/bin/nuclei -l "$file" -severity critical,high,medium,low -stats -rl 150 -c 25 -o "result/${domain}_nuclei.txt"
          done

      # Show sample results
      - name: Show Results
        run: ls -lh result && head -n 20 result/*_nuclei.txt || echo "No findings"

      # Save results as artifact
      - name: Save Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-results-${{ github.sha }}
          path: result/

      # Commit results back to GitHub
      - name: Commit Results to GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git pull --rebase origin main || true
          git add result/*_nuclei.txt
          git commit -m "Update Nuclei scan results for ${{ github.sha }}" || echo "No new changes to commit"
          git push origin main || echo "Push skipped"
