name: Nuclei - Per Domain Scan

on:
  workflow_dispatch:
    inputs:
      severity:
        description: "Global severity levels (default: critical,high,medium,low)"
        required: false
        default: "critical,high,medium,low"
      exclude_templates:
        description: "Global templates to exclude (default: http/default-logins,code,code/cves,http/cnvd)"
        required: false
        default: "http/default-logins,code,code/cves,http/cnvd"
      threads:
        description: "Number of concurrent threads per domain (default: 50)"
        required: false
        default: "50"
      parallel_domains:
        description: "Number of domains to scan in parallel (default: 5)"
        required: false
        default: "5"
      output_folder:
        description: "Folder to save results (default: result)"
        required: false
        default: "result"
  push:
    branches:
      - main

jobs:
  nuclei:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Nuclei
        run: |
          go install github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
          nuclei -version

      - name: Ensure output folder exists
        run: mkdir -p "${{ github.event.inputs.output_folder || 'result' }}"

      - name: Cache Nuclei Templates
        uses: actions/cache@v3
        with:
          path: ~/.nuclei-templates
          key: nuclei-templates-${{ runner.os }}
          restore-keys: |
            nuclei-templates-

      - name: Update Nuclei templates
        run: nuclei -update-templates || true

      - name: Load Domain Overrides
        id: domain_overrides
        run: |
          declare -A DOMAIN_EXCLUDE
          declare -A DOMAIN_SEVERITY
          if [[ -f nuclei-domain-overrides.csv ]]; then
            while IFS=, read -r domain exclude severity; do
              [[ "$domain" == "domain" ]] && continue  # skip header if present
              DOMAIN_EXCLUDE["$domain"]="$exclude"
              DOMAIN_SEVERITY["$domain"]="$severity"
            done < nuclei-domain-overrides.csv
          fi
          # Export associative arrays as strings
          for key in "${!DOMAIN_EXCLUDE[@]}"; do
            echo "DOMAIN_EXCLUDE_$key=${DOMAIN_EXCLUDE[$key]}" >> $GITHUB_ENV
          done
          for key in "${!DOMAIN_SEVERITY[@]}"; do
            echo "DOMAIN_SEVERITY_$key=${DOMAIN_SEVERITY[$key]}" >> $GITHUB_ENV
          done

      - name: Run Nuclei Per Domain in Parallel
        continue-on-error: true
        run: |
          OUTPUT_FOLDER=${{ github.event.inputs.output_folder || 'result' }}
          DEFAULT_SEVERITY=${{ github.event.inputs.severity || 'critical,high,medium,low' }}
          DEFAULT_EXCLUDE=${{ github.event.inputs.exclude_templates || 'http/default-logins,code,code/cves,http/cnvd' }}
          THREADS=${{ github.event.inputs.threads || 50 }}
          PARALLEL=${{ github.event.inputs.parallel_domains || 5 }}

          run_scan() {
            file="$1"
            domain=$(basename "$file" _live.txt)
            EXCLUDE="${!DOMAIN_EXCLUDE_$domain:-$DEFAULT_EXCLUDE}"
            SEVERITY="${!DOMAIN_SEVERITY_$domain:-$DEFAULT_SEVERITY}"
            echo "[*] Scanning $domain with threads=$THREADS..."
            timeout 5m nuclei -l "$file" \
              -severity "$SEVERITY" \
              -exclude-templates "$EXCLUDE" \
              -c "$THREADS" \
              -o "${OUTPUT_FOLDER}/${domain}_nuclei.txt" \
              || echo "[-] Scan failed or timed out for $domain, continuing..."
          }

          export -f run_scan
          find live -name '*_live.txt' | xargs -n 1 -P "$PARALLEL" -I {} bash -c 'run_scan "$@"' _ {}

      - name: Commit and Push Scan Results
        run: |
          OUTPUT_FOLDER=${{ github.event.inputs.output_folder || 'result' }}
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add "${OUTPUT_FOLDER}"/*.txt
          git diff --cached --quiet || git commit -m "Update Nuclei scan results"
          git fetch origin main
          git rebase origin/main
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Nuclei Results Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-results-${{ github.sha }}-${{ github.ref_name }}
          path: "${{ github.event.inputs.output_folder || 'result' }}/"
