name: Nuclei - Per Domain Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  nuclei:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Nuclei via Go
        run: |
          echo "[*] Installing Nuclei using Go..."
          go install github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
          echo "export PATH=$PATH:$HOME/go/bin" >> $GITHUB_ENV

      - name: Run Nuclei for each domain file
        run: |
          mkdir -p result
          for file in live/*_live.txt; do
            domain=$(basename "$file" _live.txt)
            echo "[*] Running Nuclei scan for $domain"
            $HOME/go/bin/nuclei -l "$file" -severity critical,high,medium,low -stats -rl 150 -c 25 -o "result/${domain}_nuclei.txt"
          done

      - name: Show results
        run: ls -lh result && head -n 20 result/*_nuclei.txt || echo "No findings"

      - name: Commit results back to GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git pull --rebase origin main || true
          git add result/*_nuclei.txt
          git commit -m "Update Nuclei scan results for ${{ github.sha }}" || echo "No new changes to commit"
          git push origin main || echo "Push skipped"
