name: Subfinder - Per Domain Output

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main

jobs:
  subfinder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Subfinder
        run: |
          curl -s https://api.github.com/repos/projectdiscovery/subfinder/releases/latest \
            | grep "browser_download_url.*linux_amd64.zip" \
            | cut -d '"' -f 4 \
            | wget -qi -
          unzip subfinder_*_linux_amd64.zip
          sudo mv subfinder /usr/local/bin/
          subfinder -version

      - name: Create output directory
        run: mkdir -p output

      - name: Run Subfinder for each domain
        run: |
          while read domain; do
            clean_domain=$(echo $domain | tr -d '\r') # remove carriage return if file edited in Windows
            echo "[*] Enumerating subdomains for $clean_domain"
            subfinder -d $clean_domain -silent -o output/${clean_domain}.txt
          done < input/domains.txt

      - name: Show results
        run: ls -lh output && head -n 10 output/*.txt

      - name: Commit results back to repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/*.txt
          git commit -m "Update subfinder results" || echo "No new subdomains found"
          git push
